# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: torrent.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'torrent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtorrent.proto\"2\n\x0eTorrentRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0f\n\x07peer_ip\x18\x02 \x01(\t\"Q\n\x0fTorrentResponse\x12\x14\n\x0ctorrent_data\x18\x01 \x01(\t\x12\x12\n\ntracker_ip\x18\x02 \x01(\t\x12\x14\n\x0ctracker_port\x18\x03 \x01(\t\"E\n\x0bPeerRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0f\n\x07peer_ip\x18\x02 \x01(\t\x12\x14\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x05.File\"M\n\x0cPeerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1c\n\rupdated_files\x18\x03 \x03(\x0b\x32\x05.File\"R\n\x04\x46ile\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_size\x18\x02 \x01(\x03\x12\x11\n\tfile_type\x18\x03 \x01(\t\x12\x11\n\tfile_hash\x18\x04 \x01(\t\"&\n\x11SearchFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\".\n\x12SearchFileResponse\x12\x18\n\x05peers\x18\x01 \x03(\x0b\x32\t.PeerInfo\"J\n\x11UploadFileRequest\x12\x0f\n\x07peer_ip\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\"5\n\x12UploadFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07peer_id\x18\x02 \x01(\t\"#\n\x0eGetFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"*\n\x0fGetFileResponse\x12\x17\n\x04peer\x18\x01 \x01(\x0b\x32\t.PeerInfo\"?\n\x08PeerInfo\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0f\n\x07peer_ip\x18\x02 \x01(\t\x12\x11\n\tpeer_port\x18\x03 \x01(\x05\"9\n\x15\x44isconnectPeerRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0f\n\x07peer_ip\x18\x02 \x01(\t2\xc3\x02\n\x0eTorrentService\x12/\n\nGetTorrent\x12\x0f.TorrentRequest\x1a\x10.TorrentResponse\x12+\n\x0cRegisterPeer\x12\x0c.PeerRequest\x1a\r.PeerResponse\x12\x35\n\nSearchFile\x12\x12.SearchFileRequest\x1a\x13.SearchFileResponse\x12\x35\n\nUploadFile\x12\x12.UploadFileRequest\x1a\x13.UploadFileResponse\x12,\n\x07GetFile\x12\x0f.GetFileRequest\x1a\x10.GetFileResponse\x12\x37\n\x0eUnregisterPeer\x12\x16.DisconnectPeerRequest\x1a\r.PeerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'torrent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TORRENTREQUEST']._serialized_start=17
  _globals['_TORRENTREQUEST']._serialized_end=67
  _globals['_TORRENTRESPONSE']._serialized_start=69
  _globals['_TORRENTRESPONSE']._serialized_end=150
  _globals['_PEERREQUEST']._serialized_start=152
  _globals['_PEERREQUEST']._serialized_end=221
  _globals['_PEERRESPONSE']._serialized_start=223
  _globals['_PEERRESPONSE']._serialized_end=300
  _globals['_FILE']._serialized_start=302
  _globals['_FILE']._serialized_end=384
  _globals['_SEARCHFILEREQUEST']._serialized_start=386
  _globals['_SEARCHFILEREQUEST']._serialized_end=424
  _globals['_SEARCHFILERESPONSE']._serialized_start=426
  _globals['_SEARCHFILERESPONSE']._serialized_end=472
  _globals['_UPLOADFILEREQUEST']._serialized_start=474
  _globals['_UPLOADFILEREQUEST']._serialized_end=548
  _globals['_UPLOADFILERESPONSE']._serialized_start=550
  _globals['_UPLOADFILERESPONSE']._serialized_end=603
  _globals['_GETFILEREQUEST']._serialized_start=605
  _globals['_GETFILEREQUEST']._serialized_end=640
  _globals['_GETFILERESPONSE']._serialized_start=642
  _globals['_GETFILERESPONSE']._serialized_end=684
  _globals['_PEERINFO']._serialized_start=686
  _globals['_PEERINFO']._serialized_end=749
  _globals['_DISCONNECTPEERREQUEST']._serialized_start=751
  _globals['_DISCONNECTPEERREQUEST']._serialized_end=808
  _globals['_TORRENTSERVICE']._serialized_start=811
  _globals['_TORRENTSERVICE']._serialized_end=1134
# @@protoc_insertion_point(module_scope)
